version: "3.8"
services:
  hazelcast:
    image: hazelcast/hazelcast:latest-snapshot-slim-jdk21
    ports:
    - 5701:5701
    networks:
      - hazelcast-network
      
  management-center:
    image: hazelcast/management-center:5.3.3
    ports:
    - 8090:8080
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
    - MC_ALLOW_MULTIPLE_LOGIN=true
    - MC_ADMIN_USER=admin
    - MC_ADMIN_PASSWORD=Password1#
    networks:
      - hazelcast-network
      
networks:
  hazelcast-network:
    driver: bridge