scrape_configs:
  - job_name: 'SpringBoot-Monitoring-Job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'springboot-prometheus-grafana'
